package pralka.ui;

import com.jgoodies.binding.PresentationModel;
import com.jgoodies.binding.adapter.Bindings;
import com.jgoodies.binding.value.ConverterFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.NumberFormat;
import javax.swing.Timer;
import pralka.sim.Programmer;
import pralka.sim.Simulation;
import pralka.sim.WashingMachine;

public class UserInterfacePanel extends javax.swing.JPanel {

    WashingMachine washingMachine;
    Simulation simulation;
    
    /** Creates new form UserInterfacePanel */
    public UserInterfacePanel() {
        initComponents();
    }

    public void setWashingMachine(WashingMachine washingMachine) {
        this.washingMachine = washingMachine;
        initDataBindings();
    }    
    
    private void initDataBindings() {
        PresentationModel<Programmer> model = new PresentationModel<Programmer>(washingMachine.getProgrammer());
        PresentationModel<WashingMachine> washingMachineModel = new PresentationModel<WashingMachine>(washingMachine);
        
        // wybór programu
        Bindings.bind(rbtnCotton, model.getModel(Programmer.PROPERTYNAME_CHOSEN_PROGRAM), Programmer.PredefinedProgram.PROGRAM_COTTON);
        Bindings.bind(rbtnWool, model.getModel(Programmer.PROPERTYNAME_CHOSEN_PROGRAM), Programmer.PredefinedProgram.PROGRAM_WOOL);
        Bindings.bind(rbtnDelicate, model.getModel(Programmer.PROPERTYNAME_CHOSEN_PROGRAM), Programmer.PredefinedProgram.PROGRAM_DELICATE);
        Bindings.bind(rbtnFast, model.getModel(Programmer.PROPERTYNAME_CHOSEN_PROGRAM), Programmer.PredefinedProgram.PROGRAM_FAST);
        Bindings.bind(rbtnHandWash, model.getModel(Programmer.PROPERTYNAME_CHOSEN_PROGRAM), Programmer.PredefinedProgram.PROGRAM_HANDWASH);
        Bindings.bind(rbtnCustom, model.getModel(Programmer.PROPERTYNAME_CHOSEN_PROGRAM), Programmer.PredefinedProgram.PROGRAM_CUSTOM);
        
        Bindings.bind(txtTemperature, ConverterFactory.createStringConverter(model.getModel(Programmer.PROPERTYNAME_TEMPERATURE), NumberFormat.getIntegerInstance()));
        txtTemperature.setEditable(false);
        
        Bindings.bind(chkAdditionalWash, model.getModel(Programmer.PROPERTYNAME_ADDITIONAL_WASH));
        
        Bindings.bind(txtStatus, washingMachineModel.getModel(WashingMachine.PROPERTYNAME_STATUS));
        txtStatus.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnStart = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        txtStatus = new javax.swing.JTextField();
        btnTemperature = new javax.swing.JButton();
        btnSpeed = new javax.swing.JButton();
        txtTemperature = new javax.swing.JTextField();
        txtSpeed = new javax.swing.JTextField();
        btnWashingTime = new javax.swing.JButton();
        txtWashingTime = new javax.swing.JTextField();
        chkCradle = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        rbtnCotton = new javax.swing.JRadioButton();
        rbtnWool = new javax.swing.JRadioButton();
        rbtnDelicate = new javax.swing.JRadioButton();
        rbtnFast = new javax.swing.JRadioButton();
        rbtnHandWash = new javax.swing.JRadioButton();
        rbtnCustom = new javax.swing.JRadioButton();
        chkAdditionalWash = new javax.swing.JCheckBox();
        btnStop = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnStart, gridBagConstraints);

        btnPause.setText("Pauza");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnPause, gridBagConstraints);

        txtStatus.setEditable(false);
        txtStatus.setMinimumSize(new java.awt.Dimension(600, 20));
        txtStatus.setPreferredSize(new java.awt.Dimension(650, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(txtStatus, gridBagConstraints);

        btnTemperature.setText("Temperatura");
        btnTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperatureActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnTemperature, gridBagConstraints);

        btnSpeed.setText("Prędkość silnika");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnSpeed, gridBagConstraints);

        txtTemperature.setEditable(false);
        txtTemperature.setMinimumSize(new java.awt.Dimension(60, 20));
        txtTemperature.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txtTemperature, gridBagConstraints);

        txtSpeed.setEditable(false);
        txtSpeed.setMinimumSize(new java.awt.Dimension(60, 20));
        txtSpeed.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txtSpeed, gridBagConstraints);

        btnWashingTime.setText("Czas prania");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnWashingTime, gridBagConstraints);

        txtWashingTime.setEditable(false);
        txtWashingTime.setMinimumSize(new java.awt.Dimension(60, 20));
        txtWashingTime.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txtWashingTime, gridBagConstraints);

        chkCradle.setText("Ruchy kołyskowe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        add(chkCradle, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Programy"));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 70));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 69));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        rbtnCotton.setSelected(true);
        rbtnCotton.setText("Bawełna/synteyki");
        rbtnCotton.setMaximumSize(null);
        rbtnCotton.setMinimumSize(new java.awt.Dimension(110, 23));
        rbtnCotton.setPreferredSize(new java.awt.Dimension(110, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(rbtnCotton, gridBagConstraints);

        rbtnWool.setText("Wełna");
        rbtnWool.setMaximumSize(null);
        rbtnWool.setMinimumSize(new java.awt.Dimension(110, 23));
        rbtnWool.setPreferredSize(new java.awt.Dimension(110, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(rbtnWool, gridBagConstraints);

        rbtnDelicate.setText("Tkaniny delikatne");
        rbtnDelicate.setMaximumSize(null);
        rbtnDelicate.setMinimumSize(new java.awt.Dimension(110, 23));
        rbtnDelicate.setPreferredSize(new java.awt.Dimension(110, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(rbtnDelicate, gridBagConstraints);

        rbtnFast.setText("Szybki");
        rbtnFast.setToolTipText("");
        rbtnFast.setMaximumSize(null);
        rbtnFast.setMinimumSize(new java.awt.Dimension(110, 23));
        rbtnFast.setPreferredSize(new java.awt.Dimension(110, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(rbtnFast, gridBagConstraints);

        rbtnHandWash.setText("Pranie ręczne");
        rbtnHandWash.setMaximumSize(null);
        rbtnHandWash.setMinimumSize(new java.awt.Dimension(110, 23));
        rbtnHandWash.setPreferredSize(new java.awt.Dimension(110, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(rbtnHandWash, gridBagConstraints);

        rbtnCustom.setText("Własny program");
        rbtnCustom.setMaximumSize(null);
        rbtnCustom.setMinimumSize(new java.awt.Dimension(110, 23));
        rbtnCustom.setPreferredSize(new java.awt.Dimension(110, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(rbtnCustom, gridBagConstraints);

        chkAdditionalWash.setText("Dodatkowe pranie wstępne");
        chkAdditionalWash.setMaximumSize(null);
        chkAdditionalWash.setMinimumSize(new java.awt.Dimension(160, 23));
        chkAdditionalWash.setPreferredSize(new java.awt.Dimension(160, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(chkAdditionalWash, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(btnStop, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperatureActionPerformed
        washingMachine.getProgrammer().changeTemperature();
    }//GEN-LAST:event_btnTemperatureActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        washingMachine.getProgrammer().startWashing();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        washingMachine.getProgrammer().pauseWashing();
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        washingMachine.getProgrammer().stopWashing();
    }//GEN-LAST:event_btnStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnSpeed;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnTemperature;
    private javax.swing.JButton btnWashingTime;
    private javax.swing.JCheckBox chkAdditionalWash;
    private javax.swing.JCheckBox chkCradle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnCotton;
    private javax.swing.JRadioButton rbtnCustom;
    private javax.swing.JRadioButton rbtnDelicate;
    private javax.swing.JRadioButton rbtnFast;
    private javax.swing.JRadioButton rbtnHandWash;
    private javax.swing.JRadioButton rbtnWool;
    private javax.swing.JTextField txtSpeed;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtWashingTime;
    // End of variables declaration//GEN-END:variables
}
